/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FactorialJNI */

#ifndef _Included_FactorialJNI
#define _Included_FactorialJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FactorialJNI
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_FactorialJNI_factorial
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
