/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LuaJNI */

#ifndef _Included_LuaJNI
#define _Included_LuaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LuaJNI
 * Method:    getFunctionRef
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_LuaJNI_getFunctionRef
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LuaJNI
 * Method:    apply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_LuaJNI_apply
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     LuaJNI
 * Method:    startLua
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LuaJNI_startLua
  (JNIEnv *, jobject);

/*
 * Class:     LuaJNI
 * Method:    closeLua
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LuaJNI_closeLua
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
