/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ComputationJNI */

#ifndef _Included_ComputationJNI
#define _Included_ComputationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ComputationJNI
 * Method:    sum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ComputationJNI_sum
  (JNIEnv *, jobject, jint);

/*
 * Class:     ComputationJNI
 * Method:    factorial
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ComputationJNI_factorial
  (JNIEnv *, jobject, jint);

/*
 * Class:     ComputationJNI
 * Method:    startLua
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ComputationJNI_startLua
  (JNIEnv *, jobject);

/*
 * Class:     ComputationJNI
 * Method:    closeLua
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ComputationJNI_closeLua
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
