/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class factorial {
  public static int factorial(int n) {
    return factorialJNI.factorial(n);
  }

  public static SWIGTYPE_p_lua_State init_lua() {
    long cPtr = factorialJNI.init_lua();
    return (cPtr == 0) ? null : new SWIGTYPE_p_lua_State(cPtr, false);
  }

  public static void end_lua(SWIGTYPE_p_lua_State L) {
    factorialJNI.end_lua(SWIGTYPE_p_lua_State.getCPtr(L));
  }

}
