/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class factorialJNI {
  public final static native int factorial(int jarg1);
  public final static native long init_lua();
  public final static native void end_lua(long jarg1);
}
